# -*- coding: utf-8 -*-
"""python2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lvh2vhZDvmu84UhumJoaBA2LydGOOu9_
"""

list=[2,4,6,8,10]
square=[i**2 for i in list]
print('square of the num are:',square)

cube=[i**3 for i in list]
print('cube of the num are:',cube)

